Use wrapped windows header to fix compilation for Cygwin
xload uses a windows-specific interface to obtain the load average, as
getloadavg() is not implemented for Cygwin.

Including some versions of windows.h after including X11 headers can lead to
compilation errors as 'Status' is used as a type name in Xlib.h, but a parameter
or memeber name in Windows headers.

Include X11/Xwindows.h rather than windows.h directly, which wraps it in a such
way to avoid any conflict with X11 headers.

In file included from /usr/include/w32api/minwindef.h:146:0,
                 from /usr/include/w32api/windef.h:8,
                 from /usr/include/w32api/windows.h:69,
                 from /jhbuild/checkout/xorg/app/xload/get_load.c:53:
/usr/include/w32api/winnt.h:4951:15: error: two or more data types in declaration specifiers
       DWORD64 Status;
               ^
In file included from /usr/include/w32api/minwindef.h:146:0,
                 from /usr/include/w32api/windef.h:8,
                 from /usr/include/w32api/windows.h:69,
                 from /jhbuild/checkout/xorg/app/xload/get_load.c:53:
/usr/include/w32api/winnt.h:5090:13: error: two or more data types in declaration specifiers
       DWORD Status;
             ^

Signed-off-by: Yaakov Selkowitz <yselkowitz@users.sourceforge.net>
Reviewed-by: Jon TURNEY <jon.turney@dronecode.org.uk>